In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 10.1 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 11.0 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 11.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 11.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.4 MB/s eta 0:00:00


In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape((1, 5))   # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
#2D array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [15]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
#unity matrix
np.ones((3, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#vectorized operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

#element wise addition
print("Addition: ", arr1 + arr2)

#element wise subtraction
print("Subtraction: ", arr1 - arr2)

#element wise multiplication
print("Multiplication: ", arr1 * arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]


In [12]:
##universal functions

arr = np.array([2, 3, 4, 5, 6])
#square root
print(np.sqrt(arr))
#exponential
print(np.exp(arr))
#sine
print(np.sin(arr))
#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [15]:
# array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr[0]

array([1, 2, 3, 4])

In [19]:
print(arr[0][0])

1


In [18]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
#statistical concept -normalization
# change the data to have a mean of 0 and SD of 1

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
sd = np.std(data)

normalized_data = (data - mean)/ sd
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# mean
mean = np.mean(data)

# median
median = np.median(data)

# standard deviation
sd = np.std(data)

# variance
var = np.var(data)

print(mean, sd, median, var)

5.5 2.8722813232690143 5.5 8.25


In [29]:
# logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data>5) & (data<8)]

array([6, 7])